# Generated by Django 5.2.12 on 2026-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_stripe__97887e_idx',
        ),
        migrations.RemoveIndex(
            model_name='subscription',
            name='billing_sub_stripe__abc269_idx',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_customer_id',
            new_name='paystack_customer_code',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_price_id',
            new_name='paystack_email_token',
        ),
        migrations.RenameField(
            model_name='subscription',
            old_name='stripe_subscription_id',
            new_name='paystack_subscription_code',
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['paystack_customer_code'], name='billing_sub_paystac_4f3a4d_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['paystack_subscription_code'], name='billing_sub_paystac_1421a6_idx'),
        ),
    ]
