# Generated by Django 5.2.12 on 2026-09-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_remove_subscription_billing_sub_stripe__97887e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='last_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
