# Generated by Django 5.2.12 on 2026-09-22 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['token'], name='staff_invit_token_e4e31b_idx'), models.Index(fields=['email'], name='staff_invit_email_d9b0dd_idx')],
                'unique_together': {('email', 'business')},
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_password', models.CharField(blank=True, max_length=6, null=True)),
                ('password_changed', models.BooleanField(default=False)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('permission_level', models.CharField(choices=[('managerial_access', 'Managerial Access'), ('limited_access', 'Limited Access')], default='limited_access', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('is_online', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(help_text='The business this staff member belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='business.business')),
                ('user', models.ForeignKey(help_text='The user who is a staff member', on_delete=django.db.models.deletion.CASCADE, related_name='staff_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'status'], name='staff_staff_busines_20b34e_idx'), models.Index(fields=['user', 'business'], name='staff_staff_user_id_5368bf_idx')],
                'unique_together': {('user', 'business')},
            },
        ),
    ]
