# Generated by Django 6.0.1 on 2026-03-19 06:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='receipt',
            name='receipts_server__4702da_idx',
        ),
        migrations.AlterField(
            model_name='receipt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='server_id',
        ),
    ]
