# Generated by Django 5.2.12 on 2026-05-19 22:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_create_document_model'),
        ('products', '0001_create_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.document')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_items', to='products.product')),
            ],
            options={
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['document'], name='documents_d_documen_4d5492_idx')],
            },
        ),
    ]
