# Generated by Django 6.0.1 on 2026-01-24 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('address_one', models.CharField(max_length=255)),
                ('address_two', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.URLField(blank=True, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('tax_rate', models.DecimalField(decimal_places=4, default=0.0, max_digits=5)),
                ('tax_enabled', models.BooleanField(default=False)),
                ('selected_template_id', models.CharField(max_length=100)),
                ('onboarding_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('motto', models.CharField(blank=True, max_length=255, null=True)),
                ('signature', models.TextField()),
                ('server_id', models.IntegerField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('synced', 'Synced'), ('error', 'Error'), ('deleted', 'Deleted')], default='pending', max_length=20)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
