# Generated by Django 5.2.12 on 2026-09-22 13:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock'), ('payment_due', 'Payment Due'), ('invoice_overdue', 'Invoice Overdue'), ('unpaid_invoices', 'Unpaid Invoices'), ('daily_sales_summary', 'Daily Sales Summary'), ('sales_milestone', 'Sales Milestone'), ('profit_performance', 'Profit/Performance Update'), ('sales_drop', 'Unusual Sales Drop'), ('weekly_report', 'Weekly Business Report'), ('best_selling_product', 'Best-Selling Product'), ('fast_moving_stock', 'Fast-Moving Stock'), ('restock_reminder', 'Inventory Restock Reminder'), ('stock_adjustment', 'Stock Adjustment'), ('new_customer', 'New Customer')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('push_sent', models.BooleanField(default=False, help_text='Whether Expo accepted the push. False means only the push side channel failed — the notification itself is still valid.')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(help_text='Every notification belongs to a business, not a user directly — owner and staff on the same business see the same feed.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.business')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['business', 'read_at'], name='notificatio_busines_d305f5_idx'), models.Index(fields=['business', 'created_at'], name='notificatio_busines_3c149f_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('platform', models.CharField(blank=True, choices=[('ios', 'iOS'), ('android', 'Android')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user'], name='notificatio_user_id_b5ab6f_idx')],
            },
        ),
    ]
