# Generated by Django 5.2.12 on 2026-09-15 12:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_business_currency_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('low_stock', 'Low Stock Alert'), ('out_of_stock', 'Out of Stock'), ('payment_due', 'Payment Due'), ('invoice_overdue', 'Invoice Overdue'), ('unpaid_invoices', 'Unpaid Invoices'), ('daily_sales_summary', 'Daily Sales Summary'), ('sales_milestone', 'Sales Milestone'), ('profit_performance', 'Profit/Performance Update'), ('sales_drop', 'Unusual Sales Drop'), ('weekly_report', 'Weekly Business Report'), ('best_selling_product', 'Best-Selling Product'), ('fast_moving_stock', 'Fast-Moving Stock'), ('restock_reminder', 'Inventory Restock Reminder'), ('stock_adjustment', 'Stock Adjustment'), ('new_customer', 'New Customer')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('body', models.CharField(max_length=500)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('push_sent', models.BooleanField(default=False, help_text='Whether Expo accepted the push. False means only the push side channel failed — the notification itself is still valid.')),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='pushtoken',
            new_name='notificatio_user_id_b5ab6f_idx',
            old_name='push_pushto_user_id_5da629_idx',
        ),
        migrations.AddField(
            model_name='notification',
            name='business',
            field=models.ForeignKey(help_text='Every notification belongs to a business, not a user directly — owner and staff on the same business see the same feed.', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='business.business'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'read_at'], name='notificatio_busines_d305f5_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['business', 'created_at'], name='notificatio_busines_3c149f_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_f2898f_idx'),
        ),
    ]
